language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.0
before_script:
  - dotnet restore ./test/OdataToEntity.Test
script:  
  - dotnet test ./test/OdataToEntity.Test -c Release -f netcoreapp1.1