language: csharp  
sudo: required  
dist: xenial  
mono: none
dotnet: 2.2
before_script:
  - dotnet restore ./test/OdataToEntity.Test 
script:  
  - dotnet test ./test/OdataToEntity.Test/OdataToEntity.Test.csproj -c Release -f netcoreapp2.1