language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.300
before_script:
  - dotnet restore ./test/OdataToEntity.Test 
script:  
  - dotnet test ./test/OdataToEntity.Test/OdataToEntity.Test.csproj -c Release -f netcoreapp2.1